import './evmBalanceAdapter'
import './prismaBalanceAdapter'
import './solanaBalanceAdapter'
import './bitcoinBalanceAdapter'
import './dogecoinBalanceAdapter'
import './tronBalanceAdapter'
import './cosmosBalanceAdapter'
