#!/usr/bin/env node
/**
 * Auto-create GitHub issue via GitHub REST API.
 * Usage:
 *   node scripts/auto-issue.mjs --title "Bug title" --body "Bug description"
 *   node scripts/auto-issue.mjs --file /path/to/issue-body.md --title "Bug title"
 *   node scripts/auto-issue.mjs --title "Bug" --body-file bug.md --labels "bug,frontend"
 */
import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'

const REPO = 'RingProtocol/ringwallet'
const API_URL = `https://api.github.com/repos/${REPO}/issues`

function loadEnv() {
  const envPath = path.join(process.cwd(), '.env')
  if (!fs.existsSync(envPath)) return {}
  const lines = fs.readFileSync(envPath, 'utf8').split('\n')
  const env = {}
  for (const line of lines) {
    const eq = line.indexOf('=')
    if (eq < 0 || line.startsWith('#')) continue
    const key = line.slice(0, eq).trim()
    const val = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
    env[key] = val
  }
  return env
}

function parseArgs() {
  const args = process.argv.slice(2)
  const opts = { labels: [] }
  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--title':
      case '-t':
        opts.title = args[++i]
        break
      case '--body':
      case '-b':
        opts.body = args[++i]
        break
      case '--body-file':
      case '-f': {
        const p = args[++i]
        opts.body = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : p
        break
      }
      case '--labels':
      case '-l':
        opts.labels = args[++i].split(',').map((s) => s.trim())
        break
      case '--assignees':
      case '-a':
        opts.assignees = args[++i].split(',').map((s) => s.trim())
        break
      default:
        if (args[i].startsWith('-')) {
          console.error(`Unknown flag: ${args[i]}`)
          process.exit(1)
        }
    }
  }
  return opts
}

function getGitInfo() {
  try {
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim()
    const commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim()
    return { branch, commit }
  } catch {
    return { branch: 'unknown', commit: 'unknown' }
  }
}

async function createIssue(token, opts) {
  const { title, body, labels, assignees } = opts
  if (!title) {
    console.error('❌ Title is required. Use --title "Bug title"')
    process.exit(1)
  }

  const { branch, commit } = getGitInfo()
  const autoFooter = `

---
*Auto-generated by Ring Wallet dev tooling*  
Branch: \`${branch}\` | Commit: \`${commit}\`
`
  const fullBody = (body || '') + autoFooter

  const payload = {
    title,
    body: fullBody,
    labels: labels || [],
  }
  if (assignees?.length) payload.assignees = assignees

  const res = await fetch(API_URL, {
    method: 'POST',
    headers: {
      Accept: 'application/vnd.github+json',
      Authorization: `Bearer ${token}`,
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      'User-Agent': 'ringwallet-auto-issue/1.0',
    },
    body: JSON.stringify(payload),
  })

  const data = await res.json()

  if (!res.ok) {
    console.error(`❌ GitHub API error (${res.status}):`)
    console.error(data.message || JSON.stringify(data, null, 2))
    process.exit(1)
  }

  return data
}

// ── Main ──
const env = loadEnv()
const token = process.env.GITHUB_TOKEN || env.GITHUB_TOKEN

if (!token) {
  console.error('❌ GITHUB_TOKEN not found.')
  console.error('')
  console.error('To set up:')
  console.error('  1. Go to https://github.com/settings/tokens/new')
  console.error('  2. Select scope: repo (full control of private repositories)')
  console.error('  3. Generate token')
  console.error('  4. Add to .env: GITHUB_TOKEN=ghp_xxxxxxxxxxxx')
  console.error('')
  console.error('Or set env var: export GITHUB_TOKEN=ghp_xxxxxxxxxxxx')
  process.exit(1)
}

const opts = parseArgs()

try {
  const issue = await createIssue(token, opts)
  console.log(`✅ Issue created: #${issue.number}`)
  console.log(`   ${issue.html_url}`)
} catch (err) {
  console.error('❌ Failed to create issue:', err.message)
  process.exit(1)
}
